AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdatestTestFunctionLCD8525V26Q0:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::290093585298:role/lambda-test-TestFunctionRole-DU63FKWY0RZN'
      Environment:
        Variables:
          S3_BUCKET: bucket-generic-us-east-1-290093585298
