AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://bucket-generic-us-east-1-290093585298/835e9ca8a07f90a08e962437578f65e5
      Environment:
        Variables:
          S3_BUCKET: bucket-generic-us-east-1-290093585298
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
